version: "3"
services:
 

    authentication:
        container_name: authentication
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./
        ports:
            - "4001:4001"
        volumes:
            - /app/node_modules
            - .:/app
        links:
            - mongoAuth

    mongoAuth:
        container_name: mongoAuth
        image: mongo
        ports:
            - "27017:27017"
       
    